# --- !Ups

CREATE TABLE "user" (
    "user_id" VARCHAR NOT NULL PRIMARY KEY,
    "name" VARCHAR,
    "email" VARCHAR,
    "avatar_url" VARCHAR,
    "activated" BIT
);
CREATE TABLE "login_info" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
    "provider_id" VARCHAR NOT NULL,
    "provider_key" VARCHAR NOT NULL
);
CREATE TABLE "user_login_info" (
    "user_id" VARCHAR NOT NULL,
    "login_info_id" BIGINT NOT NULL
);
CREATE TABLE "password_info" (
    "hasher" VARCHAR NOT NULL,
    "password" VARCHAR NOT NULL,
    "salt" VARCHAR,
    "login_info_id" BIGINT NOT NULL
);
CREATE TABLE "oauth1_info" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
    "token" VARCHAR NOT NULL,
    "secret" VARCHAR NOT NULL,
    "login_info_id" BIGINT NOT NULL
);
CREATE TABLE "oauth2_info" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
    "access_token" VARCHAR NOT NULL,
    "token_type" VARCHAR,
    "expires_in" INTEGER,
    "refresh_token" VARCHAR,
    "login_info_id" BIGINT NOT NULL
);
CREATE TABLE "openid_info" (
    "id" VARCHAR NOT NULL PRIMARY KEY,
    "login_info_id" BIGINT NOT NULL,
    "attributes" VARBINARY
);


# --- !Downs

DROP TABLE "openid_info";
DROP TABLE "oauth2_info";
DROP TABLE "oauth1_info";
DROP TABLE "password_info";
DROP TABLE "user_login_info";
DROP TABLE "login_info";
DROP TABLE "user";